### ISSUE TITLE
Haxe 4.2 support

### ISSUE THREAD

**Issue by darmie** [Kode/vscode-kha#26]
How soon can we expect the latest Haxe 4.2 syntax support, especially Module level statics?

**Comment by RobDangerous** [comment]
In about minus two days if you use an up to date Kha via the khaPath option or by using a project-local copy of Kha.

**Comment by darmie** [comment]
@RobDangerous I updated Kha path, it doesn't seem to fix the style check problems.

**Comment by RobDangerous** [comment]
That might well be the case but... the Kha extension doesn't do any style checks. The Haxe Checkstyle extension does that.

**Comment by darmie** [comment]
That's weird, because the problem goes away whenever I disable the Kha extension pack

**Comment by RobDangerous** [comment]
Not that weird really as Haxe Checkstyle comes with the Kha extension pack. But this repo is not about the pack, that would be https://github.com/Kode/vscode-kha-extension-pack - but I won't be able to help there either, because that just links in the extension, the extension itself is from the Haxe team.

**Comment by darmie** [comment]
Oh okay, thanks
