### ISSUE TITLE
Downloading Electron message never disappears

### ISSUE THREAD

**Issue by MathemanFlo** [Kode/vscode-kha#36]
The kha extension never stops showing this message
![grafik](https://user-images.githubusercontent.com/28649121/161977707-54331f8b-6e21-42d7-85eb-309cc4300ce4.png)
It also seems that intellisense stopped working with krom. 

How to reproduce it:

1. Set up a fresh Visual Studio Code or use an existing installation
2. Install kha extension
3. Open an Haxe source file

**Comment by RobDangerous** [comment]
Hu, just randomly opening a Haxe-file shouldn't even activate the extension.

**Comment by MathemanFlo** [comment]
Yes you are right, sorry. To be more precise I opened a source file of ArmorPaint, it is a kha project and therefore the extension gets activated.

**Comment by RobDangerous** [comment]
Let's give something simple like the Shader-example a try first before diving into the biggest project possible.

**Comment by MathemanFlo** [comment]
Oki.

1. So I cloned to shader example recursively
2. Opened VSCode
3. Installed the kha extension pack
4. Opened `Main.hx`. IntelliSense works here, so only the download issue remains.
5. The Downloading Electron message appears as shown in the screenshot below. Tried it on two different Windows PCs with VSCode 1.66 and the latest version of the kha extension (pack)
![grafik](https://user-images.githubusercontent.com/28649121/161989270-75265a05-4023-4175-94d8-2e2e2fc47fea.png)

**Comment by MoritzBrueckner** [comment]
I had exactly the same issue yesterday in VSCodium. The devtools (`Help > Toggle Developer Tools`) displayed an exception that seems to come from the "File Downloader" extension that the Kha extension uses for downloading electron. I fixed it eventually by simply downloading the [correct electron version](https://github.com/Kode/vscode-kha/blob/b6122b6a805a3e22382afab3dbc0e2e1523ef2c3/package.json#L109) myself because it happened so randomly that I thought that something was wrong with my local setup.

This was the error message:

![Screenshot](https://user-images.githubusercontent.com/17685000/162005707-aece49ef-71bb-4adb-8c9c-f8227cfe567d.png)

It is probably a good idea to show an error message in the UI in case some of the download/extraction routines fails: https://github.com/Kode/vscode-kha/blob/b6122b6a805a3e22382afab3dbc0e2e1523ef2c3/extension.js#L512-L538

**Comment by RobDangerous** [comment]
Will add that. But what about the intellisense-problem and Main not being found, I was more interested in that.

**Comment by MathemanFlo** [comment]
The issue disappeared and I'm unsure what it caused. How did I do it?

1. I updated the repository,
2.  realized that kinc make failed because the path the repository is located at has whitespaces in it. To fix this I changed https://github.com/Kode/Kinc/blob/main/make.bat to `@call "%~dp0Tools\kmake\kmake.exe" %*`
3. Restarted VSCode, then it worked again.

**Comment by RobDangerous** [comment]
Ah, evil white space. Would you like to create a pull request for the fix to make.bat, so you are credited correctly?

**Comment by RobDangerous** [comment]
Fun fun, it's Microsoft's own extension that broke: https://github.com/microsoft/vscode-file-downloader/issues/31

**Comment by RobDangerous** [comment]
The Electron download should work again now, kicked out the Microsoft-extension.

**Comment by MathemanFlo** [comment]
> Ah, evil white space. Would you like to create a pull request for the fix to make.bat, so you are credited correctly?

I don't mind, you can simply commit it yourself. It's quicker for both of us...

**Comment by RobDangerous** [comment]
You can do that kind of thing entirely on GitHub in just a few clicks. Anyway, did it myself now. I think we're done here. If the initial intellisense-problem returns, please create a new issue, this one is already too much of a mix-up.
